### ISSUE TITLE
Exclude posts from feed

### ISSUE THREAD

**Issue by mattheu** [whyisjake/Simple-Instant-Articles-for-Facebook#29]
We've added a checkbox that will store a flag in post meta and is used to hide a single post from FB. I wonder if this should be included in the core plugin? Likely to be a common request. Shall I open a pull request for this?

**Comment by whyisjake** [comment]
Are you thinking about adding the full UI for it? 

I was thinking about this same thing recently, and since we have filters to alter the main query for the feed, this probably isn't needed directly. 

Related, one thing that would be good to do, is to update the readme with some ideas of content manipulation.

**Comment by mattheu** [comment]
Also examples of how to add ads and analytics - I can have a bash at this

**Comment by mattheu** [comment]
Agreed UI isn't neccessary. I've added some documentation to the wiki on how to do various things. Happy to close this as #wontfix

**Comment by whyisjake** [comment]
Closing this for now.
